# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
            class: AppBundle\Twig\HelperVistas
            public: false
            tags:  
                -  { name: twig.extension }
    app.twig_helper_vistas:
            class: AppBundle\Twig\FilterVista
            public: false
            tags:  
                -  { name: twig.extension }
    app.locale_listener:
            class: BlogBundle\EventListener\LocaleListener
            arguments: ["%kernel.default_locale%"]
            tags:
                -  { name: kernel.event_subscriber }
