BlogBundle\Entity\Tag:
  properties:
    name:
        - NotBlank: {message: "EL nombre no puede estar vacio"}
        - Length:
            min: 2
            minMessage: "El nombre tiene que tener mas de 2 caracteres"