AppBundle\Entity\Curso:
    properties:
        titulo:
            - NotBlank: {message: "El titulo no puede estar vacío"}
            - Length:
                min: 2
                minMessage: "El titulo deter mas dedos caracteres"
        descripcion:
            - NotBlank: {message: "La descripcion no puede estar vacia"}
        precio:
            - Type:
                type: numeric
                message: "El precio tiene que ser numerico"
        